### ISSUE TITLE
When is gRPC-swift going to be beta or GA?

### ISSUE THREAD

**Issue by aalmekhlafi0** [grpc/grpc-swift#1040]
### What are you trying to achieve?

We are trying to use gRPC-Swift in the production environment and we would like to know your timeline to go GA.

### What have you tried so far?

We have tried Release 1.0.0-alpha.14, and we noticed performance degradation compared to REST. Wondering if the latest alpha releases have any performance enhancement.

**Comment by glbrntt** [comment]
Are you the using client or server? alpha.14 is pretty old by this point so I wouldn't be surprised if you saw improvements on a more recent version. In addition to that, I'm currently doing some performance work on the server.

As for a timeline, I can't give you anything more concrete than "soon".

**Comment by aalmekhlafi0** [comment]
We are using it on the client-side. Our server is running a java based gRPC service. 

I ran a quick performance test from the client for alpha.14 vs alpha.20. I couldn't see any difference in performance. Is there any work happening to enhance client-side performance?

**Comment by glbrntt** [comment]
There have been iterative performance improvements to the client between 14 and 20, nothing too substantial.

Can you share some details about how you compared with REST and what your expectations are?

**Comment by marvin-hansen** [comment]
@glbrntt  The issue is very real, Swift-gRPC is substantially slower than other implementations and, oddly enough, comes with a high variance in latency.  I opened another issue related to performance and supplied a handful of benchmarks to illustrate the magnitude of the problem.  IMHO, Swift-gRPC is not production ready yet. That said, once the performance issues are out of the way, this lib would become a clear winner. 

https://github.com/grpc/grpc-swift/issues/1066

**Comment by glbrntt** [comment]
1.0.0 has now been tagged.
