### ISSUE TITLE
Something causes call to response.wait() to throw

### ISSUE THREAD

**Issue by papalma** [grpc/grpc-swift#1230]
### What are you trying to achieve?
I am writing a Swift app (using storyboards) to send a grpc message to a server, get a response and decode the message. 
Below is the code, this is an IBAction linked to a button. 
```
    @IBAction func SendAction(_ sender: UIButton) {
        let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        defer {
          try? group.syncShutdownGracefully()
        }

        let channel = ClientConnection
            .insecure(group: group)
            .connect(host:URLTextField.text!, port:Int(PortTextField.text!.trimmingCharacters(in: CharacterSet.whitespaces))!)
        defer {
          try! channel.close().wait()
        }
        
        let pollClient = MyApp_ApiClient(channel:channel)
        let reqData = MyApp_PollRequest()
        let call = pollClient.poll(reqData)
        
        do {
            let reply = try call.response.wait() // <- THIS LINE THROWS 
            // update UI with reply
        }
        catch let error {
            print("Error. \(error)") // PRINTED MESSAGE IS : "Error. ok (0)"
        }
    }
```

The problem is when calling to call.response.wait() this always throws, the code never reach the code to update the UI. At network level, Wireshark shows that there is a message and a response with the right info, but for some reason this is being processed correctly.
Testing this service using grpcurl console application, using the same .proto file works fine.

The .proto used is this
```
syntax = 'proto3';

package MyApp;

service Api {
    rpc Poll (PollRequest) returns (PollReply) {}
}

message PollRequest { }

message PollReply {
    string models = 1;
    string data   = 2;
    int32  ts     = 3;
}
```

Thanks for your help

**Comment by Lukasa** [comment]
What error does it throw?

**Comment by papalma** [comment]
Hi Lukasa
> What error does it throw?
            The message printed is "ok (0)"

**Comment by glbrntt** [comment]
Does this reproduce consistently?

**Comment by papalma** [comment]
Yep. Every time.

**Comment by glbrntt** [comment]
> At network level, Wireshark shows that there is a message and a response with the right info, but for some reason this is being processed correctly.

With Wireshark are you capturing when using grpcurl or with grpc-swift? Do you think you could provide a pcap of the request with grpc-swift?

**Comment by papalma** [comment]
I'm capturing the messages generated by this swift app using gRPC-swift. I have tried grpcurl to test the server, the response contains data and is displayed.
I haven't found any swift app with storyboard  UI using grpc-swift as example. regarding grpc-swift, Should I have any considerations when initializing the app ?

**Comment by glbrntt** [comment]
> I'm capturing the messages generated by this swift app using gRPC-swift. I have tried grpcurl to test the server, the response contains data and is displayed.

Could you share that pcap or a complete repro for this? The error we're throwing is an 'ok (0)' status, which to me seems like the rpc is completing fine (from the perspective of the server) but for some reason the client isn't receiving (or is dropping) the response message. When it receives the final status ('ok') it fails the response promise with that the status because no response has been seen.

> I haven't found any swift app with storyboard UI using grpc-swift as example. regarding grpc-swift, Should I have any considerations when initializing the app ?

Nothing specific I can aware of but I'm not an iOS developer. Generally speaking you need to take care when managing resources, i.e. shutting down the `EventLoopGroup` and connections at appropriate times.

You should also consider using the `NIOTSEventLoopGroup` over the `MultiThreadedEventLoopGroup` -- this will use the Network.framework backend rather than BSD sockets. (See https://github.com/grpc/grpc-swift/blob/main/docs/apple-platforms.md and https://github.com/grpc/grpc-swift/blob/main/docs/tls.md if you're using TLS.)
