### ISSUE TITLE
Metadata access needed throughout the API

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#14]
The generated code currently provides very limited access to metadata. 

Both client and server code need access to metadata provided from the other side and clear mechanisms for sending it.

**Comment by pusolito** [comment]
Are there plans to add this support?  This is currently a blocker for adoption of the library.  The following are important:

- [ ] Per-call metadata manipulation
- [ ] Way for clients to access metadata returned by the server

**Comment by denismullaraj** [comment]
Is there any way for client to access metadata returned by the server?

**Comment by MrMage** [comment]
> Is there any way for client to access metadata returned by the server?

@denismullaraj Please create separate issues for questions rather than hijacking a two-year old issue.

To answer your question, if you use the asynchronous unary call, the metadata is part of the `CallResult` object: https://github.com/grpc/grpc-swift/blob/8eac348c1108e8acbe70e24970dc1fd3c384aad6/Sources/Examples/Echo/Generated/echo.grpc.swift#L109

**Comment by denismullaraj** [comment]
@MrMage Yeah I noticed that almost one hour after I made the question, I was looking for it in the result call and it was exactly there (both initialMetadata and trailiningMetadata) :) Thanks!

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
