### ISSUE TITLE
Duplicated GOAWAY from Client on graceful shut down by graces-go server

### ISSUE THREAD

**Issue by fonok3** [grpc/grpc-swift#1520]
### Describe the bug

We use a server implemented with [grpc-go](https://github.com/grpc/grpc-go) This server may gracefully shutdown the connection before shutting down itself. In the repository of [grpc-go](https://github.com/grpc/grpc-go) it is documented that the server sends two GOAWAY frames to circumvent a http2 race condition:

'''
 // A client can receive multiple GoAways from the server (see
 // https://github.com/grpc/grpc-go/issues/1387).  The idea is that the first
 // GoAway will be sent with an ID of MaxInt32 and the second GoAway will be
 // sent after an RTT delay with the ID of the last stream the server will
 // process.
'''

The grpc-swift-client responds to both GOAWAY frames with GOAWAY frames which leads the grpc-go-server to crash. E.g. the client implementation of grpc-go checks for already received GOAWAY frames and their stream ids which prevents two following GOAWAY frames by the client ([Implementation](https://github.com/grpc/grpc-go/blob/81db25066bf395f3f49a8a8125eb199547d03469/internal/transport/http2_client.go#L1244-L1271)).

Since the behavior of the grpc-swift-client causes other servers to crash we expect grpc-swift to change the behavior.

### To reproduce

Steps to reproduce the bug you've found:
1. Initiate connection
2. Make a bidirectional RPC to the server (grpc-go)
3. Invoke gracefullShutdown on the server
4. Clients sends two GOAWAY frames
5. Server crashes due to close of closed channel

We could reproduce the behaviour utilising the client from [RouteGuide-Example](https://github.com/grpc/grpc-swift/tree/main/Sources/Examples/RouteGuide) and implementing a go-server using the example proto file.

### Expected behaviour

The grpc-swift-client should only send one GOAWAY frame.

**Comment by Lukasa** [comment]
Based on your description of the server's behaviour, I think the Go implementation is in the wrong here. There is nothing incorrect in sending multiple GOAWAY frames sequentially, so long as the maximum stream IDs do not go upwards. There's no clear reason to require that we send only one GOAWAY frame here, _especially_ as the Go implementation is _itself_ sending multiple GOAWAY frames.

**Comment by zasweq** [comment]
Got the fix for the closed channel: https://github.com/grpc/grpc-go/pull/5854. However, the gRPC-Go team is still working on identifying why two goaway pings were received on the go server in the first place. Either a. we send out two goaway pings in your issue, or b. gRPC-Swift sends out two goaway pings somehow. Does your implementation send out pings after the two goaway responses (I swear I remember reading something about this) or do we send out two pings?

**Comment by Lukasa** [comment]
I'm afraid that I can't provide my Go example server easily due to a legal limitation. If you can give me a Go server you're happy for me to use as a reference I can do the rest of the investigation here.

**Comment by zasweq** [comment]
Thanks for the reply. No worries at all, but do you think you could print the frames received and sent in your system to help figure out what's going on here. This is the where the framer reads frames (can use %+v formatting directive on the whole frame for clean logs): https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L608. https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L1342 this is the only place the grpc-go Http2_Server sends a GOAWAY ping, so you can log here. I just want to derive whether the double send of goaway ping acks is due to the Swift client (where we suspect) or us sending a double goaway ping. Logging at these two places will help you derive which side has the problem.

**Comment by dfawley** [comment]
Ping on this issue.  We have fixed the panic in gRPC-Go, but I'm worried it could be papering over another issue.  The only explanation we have at the moment is that gRPC-swift is sending out multiple ping acks for a single ping, which if true should be fixed, and if not would mean we need to do further investigation on our side.

As far as debugging, on the Go server side, you should be able to simply set `GODEBUG=http2debug=2` in the environment to get a list of all the http/2 frames the server receives.

And for the Go server to test with, I was thinking you would be able to use the RouteChat modifications as mentioned in your earlier comment above: https://github.com/grpc/grpc-swift/issues/1520#issuecomment-1309093692

**Comment by glbrntt** [comment]
> The only explanation we have at the moment is that gRPC-swift is sending out multiple ping acks for a single ping, which if true should be fixed, and if not would mean we need to do further investigation on our side.

gRPC Swift _is_ emitting multiple acks. We'll fix this.
