### ISSUE TITLE
Idea: Add a SwiftNIO-based server implementation

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#172]
See https://github.com/apple/swift-nio.

At the moment, each request the server opens one dispatch thread just to wait on its `gRPC` operation queue, plus potentially more for sending/receiving data. Using SwiftNIO's planned HTTP2 implementation should avoid these threads, making the server much more scalable. Plus, given that the [gRPC HTTP2 protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) is fairly understandable, it might be easier to reason about serving that protocol directly than to reason about calling to the `gRPC-Core` library correctly.

What do you think?

**Comment by timburks** [comment]
Let's do it. There's interest and support for a pure-Swift gRPC, but we'll also need SSL/TLS. It might be worth warming up by writing an alternate proto-over-HTTP1 server using [NIOHTTP1Server](https://github.com/apple/swift-nio/blob/master/Sources/NIOHTTP1Server/main.swift).

**Comment by dcow** [comment]
I am also interested in foundation-backed or nio-backed (swift native) backend for grpc. If we did things right, on platforms with `Security.framework`, we could delegate to it for TLS. This would also mean we don't need to yank keys out of the keychain for use with boringssl. GRPC has a "transport security interface" (the `tsi_*` symbols). However, I believe the boringssl implementation is the only one so far (other than the no-security impl. for tests.)

**Comment by MrMage** [comment]
Apple already has a [library for TLS support with SwiftNIO](https://github.com/apple/swift-nio-ssl), and I expect their SwiftNIO-based HTTP2 library also to come with TLS support out of the box. So I think we won’t need to worry about this. Plus, most server-side HTTP servers nowadays delegate SSL termination to a reverse proxy in front of them, anyway (not sure if this is different for HTTP2). However, the problem with Security.framework is that it’s not available on Linux, and that’s the most interesting server-side use case for gRPC.

**Comment by dcow** [comment]
@MrMage `SwiftNIO` is actually Swift bindings _for_ `OpenSSL`.. not a Swift implementation of TLS. This means you're still using `OpenSSL` (or API-compatible friends). The reason I mentioned the GRPC `tsi` is because the real advantage of a foundation/swift-native implementation here would be to:

1. use the framework or swift-native nio apis (performance win)
2. avoid bundling openssl with your application (binary size win, security win if you can use keychain/generally available tpms on other hardware)

If we only do (1) that's nice for servers, but you leave clients in basically the same position they are today because clients don't really benefit much from NIO unless you have a client pumping massive amounts of data on many channels. And in both cases, the neither party can leverage hardware-backed trust modules (e.g. secure enclave) to perform crypto operations during the TLS handshake.

I like the idea of a full swift-native implementation of the grpc protocol much the same as `grpc-go` and `grpc-java`. This would leave things more flexible and definitely allow us to do both (1) and (2). I should add, there's likely a middle ground even if you go this route where you still support `swift-nio-ssl` for environments that aren't as resource constrained (servers) but also support foundation/security framework apis for when available so that iOS clients are not left in the cold (=

**Comment by MrMage** [comment]
IMHO, the binary size and performance improvements are negligible and I don’t think the Secure Enclave is used for any crypto functionality like that, so there are no security benefits yet, either. On the other hand, this would significantly increase the maintenance effort, having to interface with different crypto libraries. For now, I would only go with whatever SwiftNIO provides in terms of TLS support. If you’d want to use the OS libraries, that code should probably go into SwiftNIO‘S TLS code, not gRPC.

**Comment by dcow** [comment]
> IMHO, the binary size and performance improvements are negligible 

grpc is almost 10 megabytes (boringssl alone is on the upper end of 3mb). I suspect you're mostly working in a server environment if you think that's negligible. For iOS apps, that's 1/10th of the limit for apps to be downloaded over cellular. Many apps sit around upper 70s to 95 mb without grpc. Adding it can be a real strain.

> and I don’t think the Secure Enclave is used for any crypto functionality like that, so there are no security benefits yet, either. 

The keychain (backed by secure enclave when available) is absolutely used to store keys and certificates used for TSL and is hooked into the [Security.SecureTransport](https://developer.apple.com/documentation/security/1392400-sslsetcertificate) framework TLS implementation to perform the crypto operations used to sign data during TLS session establishment. The security benefit is that a compromised application does not have access to private key material and thus keys cannot be exfiltrated. 

> On the other hand, this would significantly increase the maintenance effort, having to interface with different crypto libraries.

Not if you define a nice transport security interface (`tsi`). see: https://github.com/grpc/grpc/tree/dc46c7f565196d6684d5cf6ee81e99b413ba5282/src/core/lib/security. All you have to do from a maintenance perspective is swap out the implementation and re-run tests. The work would mostly be in writing the two implementations of the tsi, and I'm here to help!!

> If you’d want to use the OS libraries, that code should probably go into SwiftNIO‘S TLS code, not gRPC.

It doesn't work that way. Traditionally an async io framework (aka. swift-nio in this case) sits _below_ the tls layer. _The byte-shoveling layer don't care_ what the bytes look like (and arguably should not even be allowed to look at them, a la sits below).  So grpc-swift (or users thereof by proxy) would have to _choose_ to use swiftnio-ssl on top of swift-nio (and indeed this is how the dependencies are structured). Conceptually it may seem like tls "belongs to" swift-nio, but it's a little more finessed than that.

To your point, it should not be swift-grpc's responsibility to implement tls. Totally agree. That falls on swiftnio-ssl or a yet to be born swiftnio-secure_transport (a fictitious Security.SecureTransport backed impl. I just made up). However, it is incumbent upon grpc-swift to allow users to "configure swift-nio" in whatever means they see fit. In this instance, that boils down to letting users choose whether they want swiftnio-ssl or swiftnio-secure_transport performing their tls. In order to do that, grpc-swift must at some level have a transport security interface, or swiftnio-ssl & swiftnio-secure_transport would need to be abi-compatible so the problem is reduced to link-time configuration. And in absence of two abi-compatible modules, you're left with a `tsi` and some glue--owned by grpc-swift.

BTW, as I was poking around the swift-nio project, I noticed it only supports:

    Ubuntu 14.04+
    macOS 10.12+


I'm not trying to sound negative. I'm wildly in favor of the work you're suggesting. However, I'm cautioning against jumping in, writing everything using swiftnio-ssl, and ending up in the same position we're in today with the core: code that was designed primarily with data-center servers in mind. Swift has a diverse ecosystem. This project needs to be compatible with resource constrained systems and it would be great if it didn't assume people were okay using openssl (via swiftnio-ssl) for everything.

Again, I'm here to help!

**Comment by MrMage** [comment]
Thanks for the elaboration! It seems like we are indeed on the same page here — switching to SwiftNIO and using whatever TLS packages are built on top of that is the end goal. And to that end, I think having API-compatible `swiftnio-ssl` and `swiftnio-secure_transport` is the way to go.

Also, thanks for the hint about `SwiftNIO`'s supported systems. The biggest goals are to be had on the server-side anyway, so I suspect that the server code will be migrated first (although that might lead to some code duplication). For the time being, I'm afraid that would probably mean that the client code would stay on `gRPC-Core` + `BoringSSL`, as a hand-coded client implementation without SwiftNIO would be more work (cause we can't build on SwiftNIO) with less benefit (cause the server-side code gains to benefit more from being rewritten). If you have other suggestions (or are willing to do that work), please drop in!

**Comment by dcow** [comment]
> and ending up in the same position we're in today with the core: code that was designed primarily with data-center servers in mind.

This is not a "stab". To clarify, I mean two things here:

1. currently grpc-swift is just swift bindings to grpc-c w/ the benefit of swift-protobufs (more: https://github.com/grpc/grpc-swift/issues/86#issuecomment-345378968)
2. the c core is pretty heavyweight (both compute and space) to use on ios. It works, for sure. But it seems appropriate for grpc-swift to consider ios clients in a way that perhaps the grpc core did not when it was first written

**Comment by dcow** [comment]
> For the time being, I'm afraid that would probably mean that the client code would stay on gRPC-Core + BoringSSL, as a hand-coded client implementation without SwiftNIO would be more work (cause we can't build on SwiftNIO)

As long as you don't break this project for the iOS users out there, sounds fine. Keep in mind you can also run servers on iOS. Albeit less common, some people use grpc for ipc or even intra-process messaging.

**Comment by SebastianThiebaud** [comment]
You're reading my mind https://github.com/apple/swift-nio/issues/55

**Comment by MrMage** [comment]
FYI, @tanner0101 from the Vapor project also asked to keep him in the loop — he is interested in providing great interoperability between Vapor (which is also migrating to Swift-NIO) and SwiftGRPC. That is also in my interest, as I'm planning to use exactly that combination.

**Comment by tanner0101** [comment]
> If we did things right, on platforms with Security.framework, we could delegate to it for TLS.

The NIO guys said this is something they are looking into. Poking them about it (an issue on the apple/swift-nio repo or otherwise) would probably help. :) I'd also love to see a macOS Security impl so that we don't have to force people to install LibreSSL on their macs for development.

As @MrMage said, I'm very interested in creating an integration with this library for Vapor. I would love to see this as an alternative to the traditional REST design that we support currently.

**Comment by jcanizales** [comment]
> grpc is almost 10 megabytes (boringssl alone is on the upper end of 3mb)

This is way way over what I measured last time for Objective-C.

@timburks Is the Swift compiler/linker not stripping unused stuff?

@muxi I think you have numbers for BoringSSL that are more recent than mine?

**Comment by jcanizales** [comment]
This also surprises me:

> the c core is pretty heavyweight (both compute and space) to use on ios. 

C gRPC has very stringent latency requirements, to be useful for datacenter infrastructure. More strict than it would make sense to impose on any mobile application. So I would expect the use of it on iOS to benefit from that, vs other HTTP/2 implementations that don't have the scaling demands that gRPC has inside Google. Thus, my _guess_ would be that, on iOS, the compute part of C gRPC is dwarfed by serialization and parsing of requests and responses. (Actually I would expect that of any HTTP/2 client). I haven't seen the numbers, though.

**Comment by MrMage** [comment]
@jcanizales Swift binaries are indeed much larger than Objective-C ones. However, I also think that we should be measuring the final size of the linked and stripped binary, not e.g. of the static libs.

But I agree that the performance of gRPC-Core should be completely fine for mobile devices.

**Comment by dcow** [comment]
@jcanizales They way I worded that is confusing. In this thread I'm referring to the "c core" as "grpc-swift as used today on top of the c core + boringssl". I don't have the numbers anymore but when I tried out grpc-swift + swift-protobufs my resulting app binary was about 10mb larger. You're right that could be swift-protobuf, I didn't dig in other than looking at boringssl too which was about 3mb IIRC.

**Comment by dcow** [comment]
And yes grpc-core works great on iOS (I'm currently using the objective-c wrapper). I'm not suggesting it's unsuitable for use there. I'm just advocating for any work that goes into rewriting grpc-swift on top of swift-nio to address some of the quirkier aspects of using grpc on iOS.

**Comment by jcanizales** [comment]
I found the numbers I measured for the ObjC library (which are very old). The size of an empty application that used gRPC + protos was ~25% the protobuf runtime, ~60% OpenSSL (I said they were old), and ~15% gRPC. At that time OpenSSL was adding ~1MB per architecture, and that was one of many reasons why we switched to BoringSSL.

That didn't have generated proto message classes, though. I know that the ObjC proto compiler generates code that uses all the runtime sorceries in the book, in order to keep the per-message per-field factor of the generated size as small as possible. Otherwise ObjC's lack of stripping would make them unusable as soon as you start using protos for everything. Swift doesn't have those runtime tricks, but it should do stripping to compensate. If it isn't, we have to do something about it in Swift protobufs.

@dcow Do you remember how many architectures were you compiling for? If those 3MB of BoringSSL were for 3 architectures or less, we absolutely need to look into what's causing the bloat.

_(All of this is orthogonal to having a non-C stack people can choose, which I fully support.)_

**Comment by dcow** [comment]
@jcanizales likely `x86_64`, `arm7`, and `arm8`. I was also looking at this on my debug build, I think. Re: compute, I was commenting on the fact that the current Swift API feels very opinionated which is fine but sometimes you need different opinions for mobile vs data center domains. I didn't mean grpc is expensive to run, again my bad on wording. I think the C API is very flexible, but some of that is lost in translation to even the objc project--even more so to this young swift project.

**Comment by MrMage** [comment]
x86 and ARM architectures shouldn't affect the same binary.

For what it's worth, my personal vision for the SwiftGRPC API is similar to Vapor's — fully asynchronous event handling with streams and futures. That should match much better with gRPC-Core streaming approach as well, and make it clearer when and how which events/errors need to be handled/waited on.

Given that NIO provides most of the necessary primitives out of the box, I think it makes sense to wait for SwiftNIO-HTTP2 to drop before implementing that, though. Otherwise we'd need to build all those primitives ourselves.

**Comment by dcow** [comment]
Here's some info I managed to generate again:

```
$ du -h Debug-iphoneos
3.5M	Debug-iphoneos/BoringSSL.framework
2.7M	Debug-iphoneos/CgRPC.framework
364K	Debug-iphoneos/Czlib.framework
8.0K	Debug-iphoneos/gRPC.framework/Headers
184K	Debug-iphoneos/gRPC.framework/Modules/gRPC.swiftmodule
188K	Debug-iphoneos/gRPC.framework/Modules
964K	Debug-iphoneos/gRPC.framework
4.0K	Debug-iphoneos/nix.framework
8.0K	Debug-iphoneos/SwiftProtobuf.framework/Headers
1.5M	Debug-iphoneos/SwiftProtobuf.framework/Modules/SwiftProtobuf.swiftmodule
1.5M	Debug-iphoneos/SwiftProtobuf.framework/Modules
8.3M	Debug-iphoneos/SwiftProtobuf.framework
 16M	Debug-iphoneos

$ du -h Debug-iphonesimulator
4.0K	Debug-iphonesimulator/BoringSSL.framework/_CodeSignature
3.8M	Debug-iphonesimulator/BoringSSL.framework
4.0K	Debug-iphonesimulator/CgRPC.framework/_CodeSignature
2.5M	Debug-iphonesimulator/CgRPC.framework
4.0K	Debug-iphonesimulator/Czlib.framework/_CodeSignature
300K	Debug-iphonesimulator/Czlib.framework
4.0K	Debug-iphonesimulator/gRPC.framework/_CodeSignature
8.0K	Debug-iphonesimulator/gRPC.framework/Headers
 92K	Debug-iphonesimulator/gRPC.framework/Modules/gRPC.swiftmodule
 96K	Debug-iphonesimulator/gRPC.framework/Modules
540K	Debug-iphonesimulator/gRPC.framework
4.0K	Debug-iphonesimulator/nix.framework
4.0K	Debug-iphonesimulator/SwiftProtobuf.framework/_CodeSignature
8.0K	Debug-iphonesimulator/SwiftProtobuf.framework/Headers
768K	Debug-iphonesimulator/SwiftProtobuf.framework/Modules/SwiftProtobuf.swiftmodule
772K	Debug-iphonesimulator/SwiftProtobuf.framework/Modules
5.1M	Debug-iphonesimulator/SwiftProtobuf.framework
 12M	Debug-iphonesimulator
```

It's just a project that uses swift-protobuf and grpc-swift circa October 2017. Looks like `SwiftProtobuf` is the biggest culprit @jcanizales but I don't think my numbers were too off. I rescind  my overly eager assertion that the "c core" is to blame. Sorry. 

```
$ lipo -info Debug-iphoneos/BoringSSL.framework/BoringSSL 
Architectures in the fat file: BoringSSL.framework/BoringSSL are: armv7 arm64

$ lipo -info Debug-iphonesimulator/BoringSSL.framework/BoringSSL 
Non-fat file: Debug-iphonesimulator/BoringSSL.framework/BoringSSL is architecture: x86_64
```

**Comment by jcanizales** [comment]
To summarize, on a debug build for iOS we have, per architecture:

500k from gRPC.framework - the C core
1.4M from CgRPC.framework - the Swift wrapper around it
1.8M from BoringSSL.framework
4.2M from SwiftProtobuf.framework - the protobuf runtime

If the numbers for a release build are in that ballpark, we need to see how to optimize pretty much the four of them.

Also, are we looking at these things how they end up in the final app, or are there intermediate build artifacts in there that might be distorting the measure? Because I wouldn't expect to see headers inside the app, not even if built for debug.

**Comment by jcanizales** [comment]
It's also curious to me that BoringSSL would be the same size when compiled for x86, as when compiled for the two arm versions added together. ¯\_(ツ)_/¯

**Comment by dcow** [comment]
> 490k from gRPC.framework - the C core
> 1.4M from CgRPC.framework - the Swift wrapper around it

I think those two are flipped (considering `gRPC` has a `.swiftmodule`).

**Comment by jcanizales** [comment]
Oh, I didn't know what swiftmodule files were. I learned something today :) Let me subtract them and edit my comment above.

**Comment by MrMage** [comment]
FYI, I have a trivial gRPC server based on SwiftNIO running now: https://github.com/MrMage/grpc-swift/blob/4dd2609483a59c64ea67e622587ec6a9dff09f97/Tests/SwiftGRPCNIOTests/EchoServerTests.swift#L38

/cc @timburks

**Comment by weissi** [comment]
@MrMage & @timburks we're really happy to see some work with grpc-swift on NIO going on here. Just wanted to let you know that if there are NIO issues or questions you hit please let us know, here to help!

**Comment by weissi** [comment]
@dcow btw, we have a NIO on Network.framework currently in testing. That will be released really soon and then on iOS and macOS (if you want) you’d use Network.framework directly with a NIO application.

**Comment by fabianfett** [comment]
I guess this is what @weissi referred to:
https://forums.swift.org/t/niotransportservices-swiftnio-and-network-framework/14567

**Comment by MrMage** [comment]
This has been implemented, partially on master and fully in the `nio` branch.
