### ISSUE TITLE
Missing SwiftProtobufPluginLibrary import in generated code

### ISSUE THREAD

**Issue by basalphenaar** [grpc/grpc-swift#179]
In a *.proto file we are defining a custom method option in the following way:
```
extend google.protobuf.MethodOptions {
    bool requiresAuthentication = 50001;
}
```
When generating the Swift code with revision `cacc80d` of grpc-swift an import for `SwiftProtobufPluginLibrary` is missing in the generated *.pb.swift file. `Google_Protobuf_MethodOptions` is being extended in the generated code but it is being marked as an undeclared type until I manually import `SwiftProtobufPluginLibrary` in addition to the already imported `SwiftProtobuf`. This is fixing the issue but since ideally the generated code is never modified manually this is not a great solution.

Is this a known issue and/or has somebody encountered this issue before?

**Comment by MrMage** [comment]
The `.pb.swift` files are generated by https://github.com/apple/swift-protobuf, not by this library. So that sounds more like an issue for that than for this repository?

Also, my understanding was that `SwiftProtobufPluginLibrary` is mostly supporting code for the Swift `protoc` codegen plugin, and not supposed to be used in client code. But I might be mistaken there.

**Comment by basalphenaar** [comment]
Ah yes, I think you're right about that, I'll report it there. You could be right about `SwiftProtobufPluginLibrary` being a supporting library for the code generation plugin, unfortunately I'm not too familiar with the internal workings of grpc-swift/swift-protobuf/protoc so I can't give a comment on that. The fact remains however that I need to import it in the generated code to make it compile.

Thanks for your help!

**Comment by MrMage** [comment]
Great! Please close this issue then.
