### ISSUE TITLE
Replace vendored dependencies with cocoapods?

### ISSUE THREAD

**Issue by bootstraponline** [grpc/grpc-swift#208]
Now that cocoapods is working (https://github.com/grpc/grpc-swift/pull/207), does it make sense to remove the vendored dependencies?

It seems like grpc-swift itself could be built with cocoapods.

**Comment by MrMage** [comment]
Server-side Swift (eg. if you'd like to build a server) and the compiler plugin use the Swift package manager instead of CocoaPods. However, it would still be nice to have SPM packages for all the vendored  dependencies instead of shipping them in the SwiftGRPC repo. Feel free to try your luck at creating a `Package.swift` manifest for gRPC-Core, but note that that will require the Swift 4.1 package definition format, as you'd need to specify different flags for C and C++ compilation. I've discussed that in other threads before, but can't link to them right now because I'm on my phone.

**Comment by bootstraponline** [comment]
> Server-side Swift (eg. if you'd like to build a server) and the compiler plugin use the Swift package manager instead of CocoaPods.

I'm proposing that we drop Swift package manager and standardize on CocoaPods. I'm not sure why SPM is used?

**Comment by MrMage** [comment]
As I said, SPD is the standard for server-side Swift development, especially on Linux. Look at e.g. Vapor and Kitura.

**Comment by bootstraponline** [comment]
Ok, looks like vendored dependencies are required then.

**Comment by MrMage** [comment]
As I said, we could still try providing `Package.swift` files for the dependencies that are currently vendored.

**Comment by bootstraponline** [comment]
My use case is `grpc-swift` on iOS apps using Cocoapods. `Package.swift` files sounds like a great idea for server side Swift, however it doesn't help with mobile. I was hoping to eliminate Swift Package Manager entirely. That seems like it's not an option since there are additional use cases in play that I was unaware of.

SPM has a bunch of limitations and is not widely used on mobile.
