### ISSUE TITLE
pRPC support

### ISSUE THREAD

**Issue by zboralski** [grpc/grpc-swift#243]
It would be great to have [pRPC](http://nodir.io/post/138899670556/prpc) support until grpc is fully supported on app engine standard.

**Comment by MrMage** [comment]
Given that pPRC seems to built on Go and is a completely different library from gRPC-Core, essentially the whole project would need to be rewritten to support this. I think that's not feasible.

Also, is it possible to run Swift code in App Engine Standard, anyway?

**Comment by timburks** [comment]
Offline we've had related discussions of #174, particularly motivated by desires to 
1. remove dependency on bundled C code and 
2. use Foundation (or UIKit) networking instead of POSIX networking to allow background downloads and conformity with any future Apple requirements about networking libraries used in iOS apps.

Like pRPC, those would be temporary until we have a native-Swift gRPC that uses Foundation networking.

**Comment by MrMage** [comment]
gRPC-Web will be supported by the NIO branch; not sure how pPRC is different and whether we want to support it.
