### ISSUE TITLE
Should we move the CgRPC package into the gRPC repository?

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#248]
This would require adding a `Package.swift` to that repo, similar to how they already have podspecs. Not sure if they want to maintain that, though. Also, at the moment our vendoring scripts still apply a few changes to the CgRPC source; not sure how we'd replicate those.

@timburks, what do you think?

**Comment by timburks** [comment]
Possible disadvantages:
- That's a big repo, so this might slightly increase times of SPM builds.
- Changes might get harder because we'd need to update two repositories if we make changes to the shim (assuming that goes with CgRPC).
- We don't have any CgRPC-level tests, so the CgRPC code in the gRPC repo would be untested by CI.

Possible advantages:
- Some other language implementation might benefit from our shim. (disadvantage: we'd have to consider that before making any changes to the shim).
- Closer integration with gRPC core, including eventually dropping all vendoring.

I haven't looked into this much, but I think we would still eventually like a full-Swift gRPC implementation, which might make this moot.

**Comment by MrMage** [comment]
These are very good points. Given that vendoring new gRPC versions is actually fairly simple thanks to the scripts you created, I think we can stick with vendoring for now.
