### ISSUE TITLE
missing required module 'CgRPC'

### ISSUE THREAD

**Issue by alqa-dash** [grpc/grpc-swift#272]
Hi!

I want to clarify CgRPC integration process for myself. I looked through threads here and didn't find anything useful. 

I get whole SwiftGRPC project into my workspace and configure headers and Linked Frameworks. This way everything is fine. 

But in my case I have to create framework which uses SwiftGRPC as a dependency framework and share it with another team. To use that custom framework they must add custom framework to Linked Framework as well as SwiftGRPC, BoringSSL, CgRPC, SwiftProtobuf. It would be ok but this is not the end of story. Additionally they should configure Header Search Paths for CgRPC include folder and copy frameworks in Build Phases. Huh.. Now it should work.  Without these steps they got "missing required module 'CgRPC'" and so on.

My question: is it possible to avoid configuring Header Search Paths and (perhaps) copying frameworks?

**Comment by JonasVautherin** [comment]
I am wondering the same thing, I believe. So if I understand correctly, you are trying the "manual integration", right?

I personally build manually in command line, with something like:

1. Clone the git repo
2. Run `make && make project`
3. Run something like `xcodebuild -target BoringSSL -target SwiftGRPC -target SwiftProtobuf -target CgRPC ...`

I end up with all four frameworks, but when I include them, CgRPC is not recognized as a module (same as you, I believe).

My solution is to create a `Modules/` and `Headers/` directory inside the built `CgRPC.framework`, copy `cgrpc.h` into `Headers/` and create the following modulemap in `Modules/` (notice the `framework` keyword):

```
framework module CgRPC {
    header "cgrpc.h"
    export *
}
```

I believe that I am doing manually what you do from Xcode (i.e. configuring Header Search Paths etc).

@MrMage: Would you have a comment on that? I must say I am not familiar with Xcode projects, so I mainly solved my issue through trial-and-error. So I'd like to have your opinion about what you think is happening and if that could be solved upstream.

Note that integrating through Cocoapods works flawlessly.

**Comment by MrMage** [comment]
No idea about this, sorry. What is the error when the header is not included? In theory, https://github.com/grpc/grpc-swift/blob/master/Sources/CgRPC/include/module.modulemap should take care of this, but maybe it's missing something. Also, could you check in the Xcode build output whether it uses https://github.com/grpc/grpc-swift/blob/master/Sources/CgRPC/include/module.modulemap or auto-generates a custom module map? Took me a while to get this right for https://github.com/MrMage/zstd/blob/swift-master/lib/include/module.modulemap, for example.

**Comment by MrMage** [comment]
@alqa-dash where does that error come up? For now, it would probably make more sense to try Jonas's suggestions first, though.

**Comment by alqa-dash** [comment]
@MrMage this error appears just right when compilation starts. I will try Jonas's advice.

I have one more question, sorry for offtopic: how can I implement grpc upload in background mode in case grpc is implemented in framework (not the application code)? E.g. customer has to upload large file and don't want to wait for its completion with application on screen?

**Comment by MrMage** [comment]
Unfortunately I have no experience with the that. Given that SwiftGRPC does not use NSURLSession, SwiftGRPC background downloads might not be right now; i.e. you might need to ask iOS to create a background task for you. But those tasks are limited to 10 minutes I think.

This should get better once there is a SwiftNIO+Network.framework-based variant of SwiftGRPC, but that's still a while out.

**Comment by alqa-dash** [comment]
Ok, I think, I can manage background mode. But there is another issue (or may be I don't know how to cook it). When I enable network throttling and set bad connection settings and try to send file, I see that couple of packets have been transmitted successfully but then I got "[TCP Previous segment not captured] and that's it. Client stops sending anything. Is it possible to address this issue?

**Comment by MrMage** [comment]
No idea. It doesn't belong in this thread, either, I think. You might want to create a simple test case with the Objective-C GRPC client library and compare results. If that one fails as well, it might make sense to ask on the gRPC-Core mailing list instead.

**Comment by Allezxandre** [comment]
I'm having the same issue. Any guidance?

I know absolutely nothing about Clang, so I just looked up the documentation and I'm probably wrong, but shouldn't 
https://github.com/grpc/grpc-swift/blob/master/Sources/CgRPC/include/module.modulemap include the `framework` keyword?

**Comment by JonasVautherin** [comment]
@Allezxandre: I don't know if it should or not, but my fix is to add it, as explained in [this comment above](https://github.com/grpc/grpc-swift/issues/272#issuecomment-406614580) :-).

**Comment by JonasVautherin** [comment]
So just for the record, [here](https://github.com/Dronecode/DronecodeSDK-Swift/blob/master/Source/build_grpc.bash) is how I build grpc for iOS manually (tag 0.4.2, for some reason). I have this script for people who don't use Cocoapods, but Carthage support (#282, #284) will make it easier to build grpc for iOS.

Note [lines 31-40](https://github.com/Dronecode/DronecodeSDK-Swift/blob/master/Source/build_grpc.bash#L31-L40), where I fix this very issue manually. I am trying to understand how that can be fixed properly in the build system.

**Comment by JonasVautherin** [comment]
@MrMage: Some more feedback. So I build CgRPC.framework, and I get the following:

    CgRPC.framework/
        ├── CgRPC
        └── Info.plist

Which results in the following build error (camera.grpc.swift is generated with `protoc`):

> /camera.grpc.swift:25:8: Missing required module 'CgRPC'

When I copy `module.modulemap` into `CgRPC.framework/Modules`:

    CgRPC.framework/
        ├── CgRPC
        ├── Info.plist
        └── Modules
            └── module.modulemap

I get:

> CgRPC.framework/Modules/module.modulemap:2:12: error: header 'cgrpc.h' not found
> error: could not build Objective-C module 'CgRPC'

If I now copy `cgrpc.h` into `CgRPC.framework/Headers`:

    CgRPC.framework/
        ├── CgRPC
        ├── Headers
        │   └── cgrpc.h
        ├── Info.plist
        └── Modules
            └── module.modulemap

I get the exact same error as above, just as if the `module.modulemap` had no effect at all.

And finally, if I add the `framework` keyword into `module.modulemap`, as suggested in my fix above and also by @Allezxandre, __the build succeeds__.

So it seems like all three changes are needed:
1. Copy `cgrpc.h` into `CgRPC.framework/Headers`
2. Copy `module.modulemap` into `CgRPC.framework/Modules`
3. Add the `framework` keyword to `module.modulemap`

One more interesting thing: if I add the `framework` keyword directly into `Sources/CgRPC/include/module.modulemap` and try to build `CgRPC.framework`, it fails because... `header 'cgrpc.h' not found` (whereas in the current `master` it builds, but fails when linking the framework in another project).

**Comment by JonasVautherin** [comment]
@MrMage: I think I am stuck on that issue. I realized that quite a few people had this issue and found a workaround by changing their header search paths somehow, which is because the `CgRPC.framework` module that is currently generated lacks the `Headers` and `Modules`.

I believe that my fix above is what we actually would want as a result of the build. I am not familiar with modules, but according to the clang documentation, the [`framework`](https://clang.llvm.org/docs/Modules.html#module-declaration)  keyword doesn't seem wrong for macOS/iOS:

> The framework qualifier specifies that this module corresponds to a Darwin-style framework. A Darwin-style framework (used primarily on Mac OS X and iOS) is contained entirely in directory Name.framework, where Name is the name of the framework (and, therefore, the name of the module).

As mentioned above, adding the `framework` qualifier breaks the build of `CgRPC`, with an error saying that "header cgrpc.h" is not found. Which is weird, because `cgrpc.h` is in `CgRPC/include`, just next to `module.modulemap`, and that seems right according to the [clang documentation](https://clang.llvm.org/docs/Modules.html#private-module-map-files):

> Module map files are typically named module.modulemap and live either alongside the headers they describe or in a parent directory of the headers they describe.

Just for the sake of it, I tried to move `cgrpc.h` into `include/Headers`, and it fixes the build, but `Headers` and `Modules` are still not copied into `CgRPC.framework`. I tried to move `module.modulemap` into `include/Modules`, too, and a whole bunch of new errors arrive regarding ARM and codegen.

Would you be able to give me some insights about how `Headers` and `Modules` are usually created and why they may be omitted here?

**Comment by MrMage** [comment]
Unfortunately, I don't have a good grasp of the problem, either. It appears that currently SwiftPM-generated Xcode projects never copy any headers; at least that's what my generated project looks like. This may have been different in the past, as one of my built frameworks still included headers from a previous build that disappeared after a clean build.

In addition, the SwiftPM source code [claims that libraries built by SwiftPM "are not real frameworks"](https://github.com/apple/swift-package-manager/blob/4a8a76472fdeae9053812acbfbdbbf197e3a3ea9/Sources/Xcodeproj/pbxproj().swift#L556), although that comment might be outdated already.

At this point, I think it would make sense to ask on the Swift Forums whether there's any best practice for building `xcodeproj` files with SwiftPM whose framework products are suitable for including in other Xcode projects. @JonasVautherin, what do you think?

**Comment by JonasVautherin** [comment]
I actually did just that :-). So here are news on my side:

* I believe "my fix" is wrong. Is works, and it is convenient to apply as a patch, but it is not the right way to do it.
* The first proposal on #44 may actually be correct (and it works). It is related to the claim you pointed out in the SwiftPM source code.
* I could probably create a ruby script that fixes it this way (maybe it would go in `fix-project-settings.rb`), but:
* It may be that Swift 4.2 solves that (but CgRPC still would require some changes): https://forums.swift.org/t/generated-xcodeproj-for-c-language-target/15192

Swift 4.2 is still in pre-release (at least Xcode 10 is), and it would imply that `make project-carthage` and the versioning of `SwiftGRPC-Carthage.xcodeproj` needs to be done with Xcode 10. But that would be a proper long-term fix, and it can already be applied now (given that the carthage support is maintained by somebody who has Xcode 10 beta).

I can probably easily do the ruby fix, too, but the risk is then that it never gets removed and the CgRPC target is never actually fixed. However, I am not sure if I am able to change `cgrpc.h` into an umbrella framework.

What's your opinion on that?

**Comment by MrMage** [comment]
If we would be able to fix this by moving to Swift 4.2 with just a few changes to this repo, that would be great. I just tried making the project with Swift 4.2 and didn't see a "Copy Headers" phase generated. I've also tried creating an empty umbrella header "umbrella.h" and changing the modulemap to:

```
module CgRPC {
    umbrella header "umbrella.h"
    export *
}
```

But then (not surprisingly) compilation of the SwiftGRPC module fails due to missing symbols, and I still don't see a "Copy Headers" step nor a "Modules" directory in the build output. In general, getting these includes into a format that Swift is happy with is a pain, especially when we are already prescribed a different format by the existing library code.

I'm really not sure what the best way to solve this would be, but right now I'm leaning towards updating the documentation to tell users to manually add the header path to the enclosing project.

What do you think?

**Comment by JonasVautherin** [comment]
> I've also tried creating an empty umbrella header "umbrella.h" and changing the modulemap to:

Did you try to remove the modulemap? Aciid says [on the swift forum](https://forums.swift.org/t/generated-xcodeproj-for-c-language-target/15192) that the modulemap is not supposed to be here (it is generated by SwiftPM).

> I'm really not sure what the best way to solve this would be, but right now I'm leaning towards updating the documentation to tell users to manually add the header path to the enclosing project.

In this case I would go for a fix similar to my previous ones: I am currently testing it [here](https://github.com/JonasVautherin/grpc-swift/tree/fix-cgrpc-xcodeproj) and will make a PR when it works.

**Comment by MrMage** [comment]
Thanks, Jonas! If anyone else can confirm this to fix their issue, we can close this issue.

While at it, should we update the "manual integration" docs to also use the Carthage Xcode project? If I understand this correctly, that project should be _easier_ to integrate into e.g. an existing iOS project than the SwiftPM-generated one?
