### ISSUE TITLE
Add Access Level to TestStubs

### ISSUE THREAD

**Issue by mdiasdev** [grpc/grpc-swift#299]
### What
I would like for all generated TestStubs to have the `open` access level by default.

### Why
Regardless of where, in the project, you house your `*.grpc.swift` and `*.pb.swift` files it is common to have the your tests in a separate target. Because separate targets are handled as different modules, and the TestStubs are generated as internal, any tests are unable to utilize the generated stubs. This especially becomes an issue with the asynchronous service requests as they are generated with `fatalError()` in their method bodies -- expecting you to override the implementation with your own.

I have considered requesting we add a Visibility flag to protoc for generating the stubs. However, I think doing so would add confusion with the existing Visibility flag. Additionally, because it is more or less idiomatic to have tests in a separate target, I think having stubs be `open` by default solves for 99% of use cases

### Additional Comments
If accepted, this seems like an excellent beginner task that I'm happy to implement.

**Comment by MrMage** [comment]
Hi Matt,

Thank you for this suggestion! Making these stubs `internal` has been a deliberate choice, as I think they shouldn't pollute a framework's public API surface. However, they can still be completely overridden by importing the containing library (called e.g. Foo) with `@testable import Foo`. This essentially makes all `internal` declarations `open` in the test, see e.g. [here](https://medium.com/practical-ios-development/how-to-write-unit-tests-in-swift-without-making-everything-public-ae218acc4ec4). Would that work for you instead of making these `open`?

Best,
Daniel

**Comment by mdiasdev** [comment]
Hi Daniel, thanks for the fast reply!

I hadn't considered that. Keeping the public API unpolluted is definitely a great reason to use `@testable import` instead of the `open` access level.

Thanks for the suggestion, I'll close this enhancement request!

**Comment by MrMage** [comment]
Glad this works for you! If you are still looking for beginner tasks later on, let me know.
