### ISSUE TITLE
Support for flatbuffers needed

### ISSUE THREAD

**Issue by takemiyamakoto** [grpc/grpc-swift#33]
Currently this library only works with protobufs. Support for flatbuffers is needed, i.e., https://github.com/mzaks/FlatBuffersSwift

Is it possible to add this?

**Comment by jcanizales** [comment]
Can one write plugins for the flatbuffer code generator, as one can do for `protoc`?

**Comment by Gurpartap** [comment]
I don't use FlatBuffers. Nevertheless, I found some relevant discussions since there's some interest from game API developers. Apparently C++ and Go already support it with gRPC: https://github.com/google/flatbuffers/pull/4082

> At least for C++ and Go, we were able to adopt the existing codegen without too much work, so hopefully for Java it is the same. – @gwvo
https://github.com/grpc/grpc-java/issues/2510#issuecomment-267638475

The overall flat buffers support is being discussed here:
https://github.com/grpc/grpc/issues/5438

**Comment by aardappel** [comment]
Agreed that would be nice.. the problem is there is an unofficial/non-conformant Swift implementation for FlatBuffers that still hasn't been integrated in the main project (ping @mzaks). It probably be beneficial for that to happen first.

@jcanizales : there is no plugin system, so far all languages are supported directly by the `flatc` compiler. PRs welcome :)

**Comment by mzaks** [comment]
I am not using grpc but I can help bring flat buffers support.
I am also almost at the state where I am willing to extends flatc with Swift generator.
Currently FlatBuffersSwift is generated with https://github.com/mzaks/FlatBuffersSchemaEditor

**Comment by mzaks** [comment]
BTW. I also ported FlexBuffers. https://github.com/mzaks/FlexBuffersSwift
This one can be used out of the box, no code generator needed.

**Comment by mzaks** [comment]
I had a look at Examples to understand how grpc works and what would be needed from FlatBuffersSwift to support it.
Generally if you use the "Simple" approach and build the messaging by hand like here:
https://github.com/grpc/grpc-swift/blob/master/Examples/Simple/Xcode/Simple/Document.swift#L152
Than you can use FlatBuffersSwift out of the box.  As @aardappel described there are some divergencies between FlatBuffers and FlatBuffersSwift. The main point is that FlatBuffersSwift support graph cycles where FlatBuffers doesn't. So if the object graph that you encode with FlatBuffersSwift is a DAG. It is compatible with FlatBuffers. If it doesn't, it is a bug and I would appreciate a bug report.

I would also strongly recommend to have a look at FlexBuffers, because it is self sufficient like JSON, implements data compaction strategies, but still gives you the main benefit of FlatBuffers - random value access with 0 parsing and almost no transient memory.

Now back to FlatBuffers.

I stated before that I am considering to contribute Swift version to FlatBuffers main repository by implementing the code generator in C++. I am considering it, because than we can keep it 100% compatible and I guess the adoption rate will be much higher. Sadly I can do it only between client projects, so it can take some time. Life would be much easier if I would work on a project which actually used FlatBuffers 😉. 
BTW the cycle support in FlatBuffersSwift was implemented due to requirements of a production I was working on at the time.

**Comment by takemiyamakoto** [comment]
Any new progress on this?

**Comment by timburks** [comment]
@takemiyamakoto, as @mzaks wrote, FlatBuffers can be used with grpc-swift now with handwritten code.  To call a unary API, you could follow the pattern in [this function](https://github.com/grpc/grpc-swift/blob/master/Examples/Simple/PackageManager/main.swift#L62). There's a server [here](https://github.com/grpc/grpc-swift/blob/master/Examples/Simple/PackageManager/main.swift#L102) in the same file.

Any progress involving code generation would require integration with [flatc](https://github.com/google/flatbuffers), and that's unlikely to happen without a plugin architecture. @aardappel, please take a look at the [protoc plugin architecture](https://developers.google.com/protocol-buffers/docs/reference/other), which you can probably completely understand from reading [plugin.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto). It's very simple. The compiler parses a [Protocol Buffer Language](https://developers.google.com/protocol-buffers/docs/proto3) file into a structure, serializes that with protocol buffers, then writes it to stdin of a plugin and waits for the plugin to write a response proto to its stdout. It's vastly more scalable than trying to integrate all target language support in one binary, and it allows different language communities to engage with your project in their own repos and languages (e.g. [Go](https://github.com/golang/protobuf), [Swift](https://github.com/apple/swift-protobuf), [Ruby](https://github.com/ruby-protobuf/protobuf)).

**Comment by aardappel** [comment]
@timburks We've integrated 8 or so languages now directly into flatc, which in terms of maintenance and consistency is a superior solution to a plugin, and it is easier for the end-user. Regardless of whether you agree with that, I don't see why we would change that approach just for the sake of Swift. It isn't hard writing a new code generator.
