### ISSUE TITLE
Stream stops receiving messages after changing connection from Wifi to Cellular

### ISSUE THREAD

**Issue by slavabulgakov** [grpc/grpc-swift#337]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
How to restart a stream after changing connection from Wifi to Cellular?

#### Question Description
I use SwiftGRPC in iOS app and I have the client like:
```
service UpdateService {
    rpc GetUpdates (UpdatesConnection) returns (stream Update);
}
```
I subscribe on connectivity state of channel:
```
updateClient.channel.subscribe { connectivityState in
...
}
```
Then I make request to create stream from server:
```
let call = try updateClient.getUpdates(UpdatesConnection()) { result in
	switch result.statusCode {
		…
	} 
}
```
When I change iPhone connection from Wifi to Cellular, the stream stops receiving messages from server but the ```connectivityState``` (subscription to connectivity state) and ```result.statusCode``` keeping silent. After few minutes ```connectivityState``` gets ```.idle``` and ```result.statusCode``` gets ```. unavailable```. When ```result.statusCode``` gets ```. unavailable``` I trying to call ```let call = try updateClient.getUpdates(UpdatesConnection())``` again, but stream doesn't receive messages anyway.
So I've added subscription on iOS network state (Reachability) and I destroy the ```updateClient``` and recreate it when connection get changed from WIfi to Cellular. Only after destroying and recreating the ```updateClient``` the stream works properly - it receive messages.
Am I doing right? Maybe my way is wrong and there is another way to restart stream after changing connection?

**Comment by rebello95** [comment]
The current issue is extensively problematic because end consumers/calls are never notified if a connection goes offline. Instead, gRPC streams/channels stay active even though they're silently offline (though not destroyed). This can result in streams appearing to hang.

I was talking to @MrMage offline earlier today about this, and there are a few ideas for how we can potentially make this a bit easier for consumers to handle (though it's not possible to solve the problem altogether as long as we're using gRPC-Core for reasons outlined above).

1. Build a system that identifies when state changes occur that cause disconnections within gRPC-Core that it doesn't know about (i.e., `online -> offline`, `cellular -> wifi`, etc.) and notifies a callback/observer about them

2. In theory, we could have the channel hook into this system and restart its underlying gRPC-Core connection. However, this brings some additional complexity:

- How do we notify the consumers of active calls using this channel of the fact that the connection is being restarted?
- If an outgoing message is currently in-flight, do we need to maintain state to retry it?
- If new calls are created or existing calls send outgoing requests, what do we do with these while the channel is reconnecting?
- If the channel fails to reconnect, how long should we wait before notifying the consumer?

3. Expose functionality from `#1`, as well as the ability to call `shutdown()` on a channel. This allows end consumers to observe the changes outlined above and manually shutdown/recreate channels as they see fit

None of these options are super ideal. At the moment, I'm leaning towards option `#3` above since it's the least complex option and still leaves room for implementing `#2` if we want to in the future. Additionally, it allows for the most customizability from the consumer perspective.

Planning to investigate this a bit more tomorrow, and I'm curious to hear other thoughts!

**Comment by anjmao** [comment]
@rebello95 You can to setup keep alive https://github.com/grpc/grpc-go/blob/master/examples/features/keepalive/server/main.go#L44 so server pings client and automatically closes the connection if client is offline.

**Comment by MrMage** [comment]
I agree that how one wants to handle this would probably be very application-specific, so letting users control the process should be advisable. We might want to provide guidance or suggestions on a "best practice" to handle this (possibly with a simple, _optional_ class that can do this for the user), but give the user to handle this themselves in a custom fashion if desired.

**Comment by rebello95** [comment]
Sounds good. I'll go ahead and do the following:

- Add functionality for shutting down channels (in PR: https://github.com/grpc/grpc-swift/pull/384)
- Implement a system that observes these types of changes on the mobile client and notifies a callback as necessary
- Write up known issues and guidance for how to avoid these on the client

**Comment by rebello95** [comment]
@anjmao that also seems like a good improvement that we could expose from SwiftGRPC (documented further within the core [here](https://github.com/grpc/grpc/blob/master/doc/keepalive.md)). It would likely aid in identifying connectivity states, but it won't fully solve the problem of channels silently disconnecting based on iOS state changes

**Comment by markschmid** [comment]
We've only just started looking into GRPC on mobile and have been running into this problem as well. Most often it is the case either if changing from WiFi to Cellular (or back) and/or if the (WiFi/cellular) signal gets weak. It seems that `Channels` can be configured e.g. with an argument [keepAliveTimeout](https://github.com/grpc/grpc-swift/blob/c401b44ea81b246b8e7fea191ea1ee11a834ee60/Sources/SwiftGRPC/Core/ChannelArgument.swift#L46) but it seems unclear if that works (and how/where notifications about it would occur).

**Comment by rebello95** [comment]
Yep @markschmid setting that would probably help with connectivity issues, but likely won't be very quick to notify you of those problems since the connection would have to time out first.

**Comment by rebello95** [comment]
Implemented the `ClientNetworkMonitor` and added some docs here: https://github.com/grpc/grpc-swift/pull/387

**Comment by rebello95** [comment]
Also want to note that there's documentation of this behavior in the Objective-C implementation, and they took a similar approach to solving this problem (though it doesn't look like they handle the case of disconnecting when switching between `3G <> LTE`): https://github.com/grpc/grpc/blob/v1.19.0/src/objective-c/NetworkTransitionBehavior.md

**Comment by rebello95** [comment]
Took a long ride this morning going around San Francisco evaluating how well iOS is able to maintain a gRPC connection. Things I noticed (pretty much confirming my comments above):
- Switching between wifi <> cellular causes connections to silently disconnect
- Switching between 3G <> LTE causes connections to silently disconnect
- gRPC does time out and shut down channels as expected in cases of poor connectivity
- Backgrounding the app and foregrounding it again a few seconds later doesn't kill the connection - previously streamed responses come in upon foregrounding
- Switching between cell towers seems to work fine and not cause a disconnection

The changes that cause silent disconnects were caught by the observer I added in https://github.com/grpc/grpc-swift/pull/387, so consumers should be able to resolve these issues by utilizing that.

I also just issued a `0.8.0` [release](https://github.com/grpc/grpc-swift/releases/tag/0.8.0) which includes these changes.

**Comment by rebello95** [comment]
Going to close out this issue since it's now documented in the readme and there are workarounds on the latest release. Feel free to re-open with new concerns!

**Comment by Najdan** [comment]
Would update to gRPC-Core 1.13.0 dependency fix this issue?

> ConnectivityMonitor is able to detect the scenario of the first issue above and actively destroy the channels. However, the second issue is not resolvable. To solve that issue the best solution is to switch to CFStream implementation which eliminates all of them.
> 
> gRPC iOS with CFStream
> gRPC iOS with CFStream implementation (introduced in v1.13.0) uses Apple's networking API to make connections. It resolves the issues with TCP sockets mentioned above. Users are recommended to use this implementation rather than TCP socket implementation. The detailed behavior of streams in CFStream is not documented by Apple, but our experiments show that it accords to the expected behaviors. With CFStream implementation, an event is always received when the underlying connection is no longer viable. For more detailed information and usages of CFStream implementation, refer to the user guide.

https://github.com/grpc/grpc/blob/v1.19.0/src/objective-c/NetworkTransitionBehavior.md

**Comment by rebello95** [comment]
Simply updating to 1.13.0 wouldn't solve this problem. The CFStream implementation mentioned might fix this issue, but it's currently gated by compiler conditionals upstream since it's marked as "experimental". If we wanted to utilize it today in SwiftGRPC, we could theoretically add branching logic for using either CFStream or the existing gRPC-Core implementation, but this would be a bit challenging given we have to support Carthage, Swift PM, and CocoaPods.

I do think that upgrading gRPC-Core to use this implementation when CFStream becomes the primary implementation upstream for iOS would be ideal, though!

**Comment by Westacular** [comment]
[According to this README](https://github.com/grpc/grpc/blob/master/src/objective-c/README-CFSTREAM.md) the CFStream implementation will be default as of 1.21.0 (which is the current in-development version)

**Comment by tsabirgaliev** [comment]
Any updates on this since gRPC-Core has already shipped with CFStream as default backend?

**Comment by MrMage** [comment]
We are still using gRPC-Core 1.19; I think CFStream is not yet enabled there.

**Comment by rebello95** [comment]
Correct, we aren't using a version of gRPC-Core with CFStream as the default. If you'd like to submit a PR updating, we're happy to review!

**Comment by tsabirgaliev** [comment]
We did smoke tests with version 0.10.0 and confirm that connectivityObserver is called when switching networks, while it doesn’t in version 0.8.0
