### ISSUE TITLE
Failed to create subchannel

### ISSUE THREAD

**Issue by pffan91** [grpc/grpc-swift#342]
#### Question Description
I've created request as:

```
        let client = Service_Frontend_FrontendServiceClient(address: "backend.server.com:443", secure: true)
        
        var request = Service_Frontend_LoginRequest()
        
        var facebook = Service_Frontend_FacebookAuthData()
        facebook.facebookAuthToken = user?.userToken ?? ""
        request.authData.facebookAuthData = facebook
    
        do {
            try client.login(request) { (response, result) in
                print("Response: \n \(response)")
                print("Result: - \(result)")
            }
        } catch {
            print(error)
        }

```

After that I receive response as `nil` and result is:

```
 - successful, status unknown: Failed to create subchannel
initialMetadata: [:]
trailingMetadata: [:]
```

So where I am wrong? Can you guide me? Thank you!

**Comment by MrMage** [comment]
For me, this only happens when I don’t have an internet connection to that server. Would that explain it?

**Comment by pffan91** [comment]
The problem with App Transport Security I think.. The same code runnig on MacOS without any problems.. Any thoughts how to fix it on iOS?

**Comment by pffan91** [comment]
The issue was in calling wrong method. I used this one:

```
 try client.login(request) { (response, result) in
               print(“Response: \n \(response)“)
               print(“Result: - \(result)“)
           }
```

But looks like it does not worked.. When I changed it to 

  ```
let response = try client.login(request)
           print(response.authToken)
```

I successfully received response:)

**Comment by phlippieb** [comment]
@pffan91 I ran into the same issue, and figured out what is really happening. The problem wasn't that I was calling the wrong method; the sync and async versions of an rpc are equally valid, and in many cases we should prefer the async version. The problem was that I didn't retain the object that was making the call. For an async call, this caused the caller to be deallocated before the call could be made properly, and that produced the error in question. Using the sync call _appeared_ to fix it because, now that the call was blocking, the caller couldn't get deallocated before the call completed; however, we shouldn't block control flow while we wait for a network call to complete just as a workaround for an object not being retained.

The actual solution is simply to make sure that whichever object is making the call is retained somewhere.

Say you have a class responsible for making the call:

```
class LoginEnpoint {
   func login(request: Request) -> Void) {
      try! client.login(request) { (response, result) in
         // ...
      }
   }
}
```

Then the following will cause the endpoint object to be deallocated immediately, and the call to fail:

```
LoginEndpoint().login(request) // Failed to create subchannel
```

But retaining the endpoint object somewhere (eg as a property in your view controller) fixes it:

```
class LoginController: UIViewController {
   let endpoint = LoginEndpoint() // Retain the object

   func doLogin() {
      self.endpoint.login() // The call now works!
   }
}
```

**Comment by Ten0** [comment]
> The problem was that I didn't retain the object that was making the call. For an async call, this caused the caller to be deallocated before the call could be made properly, and that produced the error in question.

I have the same issue in another grpc-core based implementation.
This is a very insidious error. I feel like there should be some reference counting involved to avoid this behaviour.

**Comment by MrMage** [comment]
This behavior will be improved by #631, which keeps the channel active until all requests have finished.
