### ISSUE TITLE
iOS support 1.0.0-alpha.2

### ISSUE THREAD

**Issue by nakkht** [grpc/grpc-swift#541]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Is iOS supported with v1.0.0-alpha 2 version?

#### Question Description
Hello,

I wanted to know whether iOS is supported with v1.0.0-alpha 2. If not, what is missing?
Would you suggest rather to stay with 0.9.1?

**Comment by weissi** [comment]
I think @glbrntt wrote an iOS app with 1.0.0-alpha.2 through Xcode 11's support for SwiftPM packages. @glbrntt was there anything to consider?

**Comment by glbrntt** [comment]
@nakkht it depends what you mean by supported, it's still pre-release at the moment but we'll try to fix any issues and add missing features as soon as we can. We can't, however, make any guarantees about not breaking the API before releasing v1.0 (and we're not certain when that will be). There's an issue (#526) which is tracking that which may be useful to follow.

@weissi is correct: I didn't have any issues with it on iOS with Xcode 11 and SwiftPM, it worked as expected.

In terms of which you should use I think it depends on your use case: if you're already using the 0.x series then I'd stick with that a little while longer; it will undoubtably be a pain to switch from 0.x to 1.y since it's such a large change. If you're just trying out gRPC Swift then try the alpha release since we don't plan on supporting 0.x in the future beyond bug-fixes etc.

**Comment by nakkht** [comment]
@glbrntt by supported I mean being able to build(at least with latest stable Xcode) and run app with swift grpc framework, including issuing basic requests to the server and getting response back.
Breaking APIs is expected on alpha, thus this is as well used in experimental branch of my application.
Thanks for linking an issue and for the suggestion.

Did you manage to run it on iOS with Xcode 10(10.3) by any chance? I believe Xcode 11 is still in beta.
I followed the [guide](https://github.com/grpc/grpc-swift/tree/MrMage-patch-1#manual-integration):

- [x] Built an Xcode project: ```swift package generate-xcodeproj```
- [x] Added the generated project to the workspace where my project resides
- [x] Added GRPC.framework to 'Linked Frameworks and Libraries' section' (Not sure if that's what Add a build dependency on GRPC means)
As a results, I can the following error:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CNIOBoringSSLShims.h"
        ^
/Users/--/Library/Developer/Xcode/DerivedData/--/Build/Products/Debug-iphonesimulator/CNIOBoringSSLShims.framework/Headers/CNIOBoringSSLShims.h:17:10: error: 'CNIOBoringSSL/ssl.h' file not found
#include "CNIOBoringSSL/ssl.h"
         ^
<unknown>:0: error: could not build Objective-C module 'CNIOBoringSSLShims'
```
I've checked `Header Search Paths' on CNIOBoringSSLShims and they seems to point to correct CNIOBorringSSL path.

**Comment by glbrntt** [comment]
@nakkht sorry for the delay on this one, it took a fair bit of figuring out and had to be fixed upstream: https://github.com/apple/swift-nio-ssl/pull/122

After you pull in that change you should be able to build a functioning app using the nio branch and Xcode 10.3.

**Comment by nakkht** [comment]
@glbrntt great work!
Tried building manually and running ```Swift GRCP 1.0.0-alpha.3``` with ```swift-nio-ssl v2.3.0``` dependency on a simulator. Worked as expected and did not encounter any issues. 
Thanks for the help!
