### ISSUE TITLE
Errors not being passed for streaming services

### ISSUE THREAD

**Issue by jibben** [grpc/grpc-swift#565]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
Server errors are not being passed through when a streaming service ends with an error status. I noticed a FIXME comment in the test case that confirms this as the behavior:
https://github.com/grpc/grpc-swift/blob/master/Tests/SwiftGRPCTests/ServerThrowingTests.swift#L149

Is there an outstanding to-do for this? This is a pretty glaring issue as it is preventing me from performing proper authentication handling client-side (I want to pass back an UNAUTHENTICATED GRPC status, which the iOS client could then handle).

I omitted the log information as it wouldn't be helpful here, seeing as this is a known issue.

**Comment by glbrntt** [comment]
Which branch are you using here? The NIO based code on `master` is pretty old and and not production ready; I'd strongly recommend switching to the `nio` branch.

**Comment by MrMage** [comment]
To be honest, this is kind of expected behavior — if you want to know the error, you will receive it in the callback passed to the original call (see https://github.com/grpc/grpc-swift/blob/5d1f76b60e8dce2b53f67e6b8198a2c2d35f0387/Tests/SwiftGRPCTests/ServerThrowingTests.swift#L134). `receive()` will only throw in very rare circumstances; if the stream terminates for whatever reason it will simply return `nil`.

I don't think we will change this; consider switching to the `nio` branch instead.
