### ISSUE TITLE
NIO: Custom encoder / decoder for proto messages

### ISSUE THREAD

**Issue by anjmao** [grpc/grpc-swift#639]
**Problem**
Currently there is no way to pass custom protobuf message encoder / decoder. For example UnaryCall accepts request field which is of type Message from SwiftProtobuf. As Message have extension method serializedData there is no way to override it.

**Motivation**
I have react native iOS application which uses protobufjs to create actual protobuf objects in JS side. After object is created it's serialized to bytes buffer and passed to native iOS side. In current grpc-swift version (master branch) I use low level api with Channel and custom call handlers to simply pass this data into http2 transport. Similarly after I get response I do not decode it directly but pass bytes buffer to JS side there actual decoding happens. It works fine except the fact that I have a lot of custom code, but after I tried to migrate to nio I ended up changing core logic like WriteState.write since it also accepts Message protocol.

**Possible Implementation**
It would be great if we could use custom encoder / decoder which is configurable via ClientConnection.Configuration or simpler protocol for base Message which would allow to override serializedData method etc. If this issue is something that could be addressed I could help implementing it.

**Comment by MrMage** [comment]
I'm not 100% sure how this would work in practice, given that the codegen still needs a protobuf message type to use.

However, @glbrntt and I have been discussing at least allowing for method calls to take `Data` as the request/response types. Would that (potentially) help with your use case?

**Comment by glbrntt** [comment]
> However, @glbrntt and I have been discussing at least allowing for method calls to take `Data` as the request/response types.

Just to be clear: we were considering defining a `GRPCMessage` or similarly named protocol to use instead of `Message`, the type would not be restricted to `Data`.

> **Problem**
> Currently there is no way to pass custom protobuf message encoder / decoder. For example UnaryCall accepts request field which is of type Message from SwiftProtobuf. As Message have extension method serializedData there is no way to override it.
> 
> **Motivation**
> I have react native iOS application which uses protobufjs to create actual protobuf objects in JS side. After object is created it's serialized to bytes buffer and passed to native iOS side. In current grpc-swift version (master branch) I use low level api with Channel and custom call handlers to simply pass this data into http2 transport. Similarly after I get response I do not decode it directly but pass bytes buffer to JS side there actual decoding happens. It works fine except the fact that I have a lot of custom code, but after I tried to migrate to nio I ended up changing core logic like WriteState.write since it also accepts Message protocol.

I think your problem and motivation for this are sound and this is something we _should_ provide support for. However @MrMage is correct, the codegen would still need a protobuf message to use. 

If we enable support for this it would be via lower level mechanisms. It's unclear to me exactly what those would look like at the moment. Our plan for tagging 1.0.0 is to have a limited public API exposing only the high level types. Once we're happy that the internals are solid then we can gradually open up the API to expose those lower level types so that we support use cases like this.

To be clear: this is something we should support but it won't be in v1.0.0.

**Comment by MrMage** [comment]
That puts it way better than I have done; sorry for the confusion!

**Comment by glbrntt** [comment]
Hey @anjmao - it's now possible to skip the deserialization and just get the message bytes. Take a look at [this test](https://github.com/grpc/grpc-swift/blob/4602c5c6ead27c0cc2de69078ef6a248424d6230/Tests/GRPCTests/GRPCCustomPayloadTests.swift#L87) for an example of how to do this. Note that this hasn't reached a tagged release yet.
