### ISSUE TITLE
Crash on ev_poll_posix.c :: pollset_reset

### ISSUE THREAD

**Issue by dhavalcue** [grpc/grpc-swift#66]
`GPR_ASSERT(pollset->shutting_down);` was being hit.

Looking into `ev_poll_posix.c`'s history, it looks like it was fixed here: https://github.com/grpc/grpc/commit/e272af07c77af238209fce05af4cc9fee372a948

Two questions: 
1) Core gRPC seems to be at least 2 months behind, are there any plans to keep this updated.
2) Are there any plans to make `grpc-swift` a fully supported member of gRPC?

I love gRPC and using it directly at the Swift layer instead of bridging it with ObjC has a lot of advantages. But I'm a little wary of shipping with this dependency since it doesn't look like this library is supported.

**Comment by timburks** [comment]
The vendored gRPC is updated to 1.6.0 in master and [this release](https://github.com/grpc/grpc-swift/releases/tag/0.2.1). Vendoring is largely automated in the vendor-boringssl.sh and vendor-grpc.sh scripts, but the update from 1.0 recent versions required some code changes.

We're developing grpc-swift outside of the core gRPC team, and since the grpc/grpc repo has gotten quite large, it seemed best to start the project in a separate repo. Whether it goes into the main repo or other languages come out into their own repos is an open question.

Please reach out to me (timburks@google.com) or gRPC PM Varun Talwar (varuntalwar@google.com) by email with any support-related requests or comments.

**Comment by dhavalcue** [comment]
Thank you for updating to 1.6.0, helped our team a TON!
