### ISSUE TITLE
Production readiness and 1.0 version tagging

### ISSUE THREAD

**Issue by lambrusco** [grpc/grpc-swift#711]
### Question Checklist

- [X] Updated grpc-swift to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [X] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Production readiness and 1.0 version tagging

#### Question Description
Hi, I would like to know if the current NIO branch can be actually considered production ready.
I know the README states that but the 1.0.0-alpha.9 tag does not really reassure that.
I would like then to ask which are the bugs/features that are currently missing before the NIO branch can be tagged as 1.0.0 in the master branch.

Many thanks

**Comment by glbrntt** [comment]
Hey @lambrusco, 

We absolutely consider it production ready! The reason we're still using an `-alpha` tag is that there are a couple of features that we'd like to have which may break public API. Since we follow semantic versioning we'd rather not have to release a major version soon after tagging 1.0. To note, when I say breaking public API here, we don't expect to break it in any significant way. By that I mean it's highly unlikely you'll have to rewrite everything, but you may have to apply a fix-it in Xcode, for example.

There are a couple of missing features:
- compression (this is in progress)
- back pressure
- load balancing
- helpers for testing (testing is still possible, it just requires more boilerplate than we'd like)
- interceptors (e.g. to verify headers contain correct authentication information)

@MrMage do you have anything to add here?

**Comment by MrMage** [comment]
Sounds good to me. Not sure if we need all of these before 1.0, but we at least want to be confident that we can add them post-1.0 without breaking the API.

**Comment by glbrntt** [comment]
Good point: I should've clarified that the items on the list aren't all required for 1.0.0. I _think_ the only thing on the list besides compression that should be done before 1.0.0 is back pressure.

**Comment by zocario** [comment]
Hello regarding this issue I also wanted to have the confirmation we can use the 1.0.0-alpha 12 in production. From what I understand this is production ready but not released as stable because you don't want to introduce breaking changes? Having an alpha tag for starting using a project in production doesn't make me confident in using it to be honest 😅

**Comment by glbrntt** [comment]
> this is production ready but not released as stable because you don't want to introduce breaking changes? 

That's an accurate assessment!

> Having an alpha tag for starting using a project in production doesn't make me confident in using it to be honest 😅

I totally understand that viewpoint; we're hoping to tag 1.0.0 in the next couple of weeks.

**Comment by vyshane** [comment]
Will back pressure support be in the 1.0.0 release?

**Comment by glbrntt** [comment]
> Will back pressure support be in the 1.0.0 release?

No. This needs a fair bit of work; some exploratory work was documented in https://github.com/grpc/grpc-swift/issues/763.

**Comment by glbrntt** [comment]
Closing as 1.0.0 has now been tagged.
