### ISSUE TITLE
watchOS support?

### ISSUE THREAD

**Issue by Bricon66** [grpc/grpc-swift#853]
### What are you trying to achieve?

I'm trying to communicate with a grpc server running on my local laptop via a watchOS only application.

### What have you tried so far?

I have tried a few different things to troubleshoot:

Using the exact same code(a swift package that handles the grpc communication) with:

- An iPhone application both simulator and physical device - grpc communication success
- A watchOS simulator - grpc communication success
- I also (modified the code to remove the grpc request and replaced with a standard HTTP) successfully made a standard HTTP GET request to a server running on the same host as the grpc server using the physical watch only 

Maybe my question is better directed to a forum on simulator vs. physical device differences, but thought it was worth a question here to see if there is anything at the library level that might be causing an issue.

I just keep seeing transient failure errors when attempting to send, but I added some network monitoring code:
`            let monitor = NWPathMonitor()
            monitor.start(queue: .global(qos: .utility))
            monitor.pathUpdateHandler = { path in print("path changed: \(path.debugDescription)") } `

and I notice the following differences between the simulator and the device:

- simulator (success): path changed: satisfied (Path is satisfied), interface: en0
- physical watch (failure): path changed: unsatisfied (Path was denied by NECP policy), interface: ipsec2, ipv4

I tried fiddling with various App Transport Security Settings.  The connection is strictly http/insecure (for now anyway).  

Any help or suggestions would be greatly appreciated.

**Comment by Lukasa** [comment]
Hi @Bricon66, thanks for your interest in grpc-swift.

It seems like you're running into the networking restrictions in watchOS. When networking was added to watch apps in watchOS 6 this networking was added for media streaming apps specifically. If your application is a media streaming application, please watch [Streaming Audio on watchOS 6 from WWDC 2019](https://developer.apple.com/videos/play/wwdc2019/716/) for more details on what is required from your app in order to get watchOS networking to function.

When combining the material in that session with grpc-swift, remember that grpc-swift will use Network.framework. Thus, you should treat it as though it's Network.framework: whenever you'd create an `NWConnection`, instead you can create your grpc client.
