### ISSUE TITLE
Question: Is it safe to use this in iOS?

### ISSUE THREAD

**Issue by edopelawi** [grpc/grpc-swift#86]
Hi all,

I'm currently trying to integrate the `0.1.13` version to my Swift 3 iOS app. I successfully linked the dependencies, but I got ~400 warnings on build:

-  BoringSSL has 388 Value Conversion issues, mostly on integer precision.
- Czlib got three Value Conversion issues (integer precision too), and one Semantic issue caused by shifting negative value.
- CgRPC got 22 issues from Apple Mach-O Linker Warning.

I'm currently trying to hit my gRPC server using this implementation, but I want to make sure that these warnings wont cause problems in the future... or perhaps, is there a way to fix these warnings for iOS target? Is it because I'm trying to build for ARM architecture?

Thanks!

**Comment by jcanizales** [comment]
CC: @muxi

**Comment by dcow** [comment]
My experience integrating this into an iOS build was not great (and I also encountered a similar warning situation, but that's quite normal when adding c code to an iOS project). Some things to note:

* my guess is that this is primarily developed on macOS at the moment since it does not integrate into an iOS environment without modifications to the generated xcode project
* this is not yet a foundation-native implementation (will it ever be?) so you pay the size penalty of including boring-ssl and czlib (which reduces the advantages of this to simply: swift language wrappers for the existing stuff and swift-native protobufs thanks to apple-protobuf)
* there seems to be some issue right now with the visibility modifier options to the grpc-swfit protoc plugin, but I haven't investigated further yet
* contributions over life of the project have overwhelmingly been from the sole maintainer @timburks and activity has tapered off since the beginning of the year. this raises questions about commitment to this project at the grpc org level--would be great to see the community chip in of course
* however in order for the community to contribute we need an idea of what the roadmap and milestones look like and generally what the plan is to take this from experimental to stable. I emailed the maintainer a few weeks ago with some of these questions but have yet to receive a response (I did bump earlier today)

That said, it definitely works. And it's awesome to see this project underway. I am just starting to dig into whether there is support yet for monitoring channel status and doing mutual TLS (both of which are supported in the java implementation if you're imagining an Android analog).

**Comment by edopelawi** [comment]
Hey @dcow, thanks for the elaborate response! I got my hands full with the project, and got some issues on the "one per service". Thanks for pointing it out!

Another quirks to note:

- On the latest Swift 3 version (0.1.13), failing to close the channel properly when running in a Simulator might cause a crash on next run. I got `ImageMachO` related issue, and the only way to fix this is by closing the Xcode, clearing DerivedData folder, and run it again.

- `cgrpc_channel_destroy` in Channel deinit block could take a while, which will block UI if it's ran in main thread. I'm currently finding a way to make the deinit process executed in background thread... hopefully it won't create any memory leak later 🤞 

I hope this could help someone in the future. And yes, it works on iOS.
