### ISSUE TITLE
Error handling on bidirectional streams

### ISSUE THREAD

**Issue by decanus** [grpc/grpc-swift#958]
If my GRPC server sends an error, how do I handle this in swift in a bidirectional stream?

**Comment by glbrntt** [comment]
Any error sent from the server will be as a status code and optionally a message as well. The `status` property on each call object will provide that as an `EventLoopFuture<GRPCStatus>`.

**Comment by decanus** [comment]
So I can just listen to the event loop from the initial message sent?

**Comment by glbrntt** [comment]
> So I can just listen to the event loop from the initial message sent?

What are you trying to achieve here? Work out if sending a message failed, or how to act on errors that originate on the server?

**Comment by decanus** [comment]
Both, so I noticed that I can call `call.status.whenCompleted` does that get called every time a call is sent and it completes? or do I need to set whenCompleted multiple times?

**Comment by glbrntt** [comment]
The `status` future will get fulfilled exactly once per RPC; it is always the final future on the RPC that will completed. Note that we also guarantee that the `status` future will _never_ be failed (i.e. you can safely use `whenSuccess` and ignore the failure path).

To know whether sending a message on an RPC fails you can add a callback to the future returned by `sendMessage`.

**Comment by danhalliday** [comment]
I’m struggling with this issue, having migrated to GRPC Swift from an older implementation that was present in the sample code for Google Cloud Speech (https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/speech/Objective-C/Speech-gRPC-Streaming).

Why is it that the `handler` that is part of the client is never called with errors? The `.hasError` property on `Google_Cloud_Speech_V1_StreamingRecognizeResponse` is always false, even if I, say, use a blank API key. 

Here’s the client I’m using that comes with Google Cloud Speech:

```swift
public protocol Google_Cloud_Speech_V1_SpeechClientProtocol: GRPCClient {
    // ...
    func streamingRecognize(
        callOptions: CallOptions?,
        handler: @escaping (Google_Cloud_Speech_V1_StreamingRecognizeResponse) -> Void
    ) -> BidirectionalStreamingCall<Google_Cloud_Speech_V1_StreamingRecognizeRequest, Google_Cloud_Speech_V1_StreamingRecognizeResponse>
}
```

**Comment by glbrntt** [comment]
@danhalliday the handler is for _response messages_. `error` and `hasError` are properties on the `Google_Cloud_Speech_V1_StreamingRecognizeResponse`  response message. As such they indicate speech recognition errors rather than errors for the RPC as a whole.

If, for example, you use a blank API key, then you won't receive any of these messages in the handler, instead the `status` future on the call object returned from `streamingRecognize` will be completed with a relevant status code and message (i.e. unauthenticated).

**Comment by danhalliday** [comment]
Thank you this is very helpful. Do I also need to add the `whenFailure` callback to make sure I catch every possible error, or is the `whenStatus` sufficient? I don’t seem to be able to cause anything to be sent to `whenFailure`.

I also noticed I can catch errors using `.withErrorDelegate` on `ClientConnection`. Does this offer any advantage? This mechanism seems to return `GRPC.GRPCError`s rather than `GRPCStatus`s.

**Comment by glbrntt** [comment]
`whenSuccess` is fine for the `status` future, internally we'll recover any failure into an appropriate status.

The error delegate will receive all errors from the client, some of which which may come from the connection as opposed to an individual RPC made using that connection. Also the delegate will usually offer a more specific error than anything pointed to by the `GRPCStatus`, so it can be useful to look at when debugging etc.

**Comment by danhalliday** [comment]
Thanks again for your help on this @glbrntt. The distinction between the functions of the client error delegate and call status makes sense in principle. In my testing, I found the error delegate just duplicated the same errors as the status, and I couldn’t seem to make anything happen that was only reported to the error delegate, so for now I’m ignoring its output (at least for control flow).
