### ISSUE TITLE
Leaking promise encountered when running the HelloWorld Client/Server example.

### ISSUE THREAD

**Issue by Martin3498** [grpc/grpc-swift#963]
I'm getting an error message while running the HelloWorld Client/Server example. I first start the server:

`swift run HelloWorldServer`
It starts up normally:
`server started on port 62298`

Then I run the Client:
`swift run HelloWorldClient 62298`
and I receive the output:
`Greeter received: Hello stranger!
Fatal error: leaking promise created at (file: "~/Sources/GRPC/ConnectionManager.swift", line: 90): file ~/Sources/GRPC/ConnectionManager.swift, line 90
Illegal instruction: 4`

The client then exits. It is expected that the "Hello stranger!" message would be displayed without the leaking promise error message. 

When this error message is encountered, the Server does not output any error messages, nor does it exit. The Client can be run multiple times, generating the same error message each time, with the Server continuously running. Both the Client and Server are running on the same machine.

It looks like the bug was introduced as of commit `e6fa863e` (5/21/20); commits before this date do not appear to exhibit this issue. The current build (`6ea62df`) still has this issue.

The error persists even if I create my own messages in the `helloworld.proto` file (and associated functions), and recompile as needed.

I'm using:
Swift 5.2.4
Protoc 3.13.0
MacOS 10.15.6

**Comment by Lukasa** [comment]
My gut feeling is that there is a case missed in the client method handling code around application shutdown. Specifically, the program exits very shortly after printing the `Hello stranger!` message, but it tears down the ELG first. I think that the client connection manager doesn't do a good job of managing that state very well.

It seems like a call to `channeIInactive` in `ConnectionManager` will transition us into the `.transientFailure` state in preparation for reconnection. This state allocates a promise, which shortly after is leaked when the owning handler is removed from the pipeline. Fixing this is kinda tricky: we need a way to signal to the `ConnectionManager` that the application is being torn down and so that promise must be completed.

**Comment by Lukasa** [comment]
@glbrntt will be back tomorrow and he knows the architecture here a bit better than I do, but this appears to suggest we need a bit better lifecycle management.

**Comment by glbrntt** [comment]
@Lukasa's diagnosis is correct. Fortunately we do have a way to signal to the `ConnectionManager` that the application is being torn down, we just never called it which makes for a pretty poor example.
